---
- name: "Move files to server"
  become: true
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start