version: 2.1

orbs:
  slack: circleci/slack@4.2.0
            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm install
      - run:
          name: Compile the frontend code
          command: |
            cd frontend
            npm run build
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
            cd backend 
            npm install
      - run:
          name: Compile the backend code
          command: |
            cd backend
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Front end Test Install
          command: |
            cd frontend
            npm install
      - run:
          name: Front end code Run
          command: |
            cd frontend
            npm run test
      - store_test_results:
          path: ./frontend/test_results
      - store_artifacts:
          path: ./frontend/test_results

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Back end Test Install
          command: |
            cd backend
            npm install
      - run:
          name: Back end code Run
          command: |
            cd backend
            npm run test
      - store_test_results:
          path: ./Backend/test_results
      - store_artifacts:
          path: ./Backend/test_results  

  analyze-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Frontend Analyze
          command: |
            cd frontend
            npm install
      - run:
          name: Analyze the Frontend code
          command: |
            cd frontend
            npm audit --audit-level=critical 
      - slack/notify:
          event: fail
          template: basic_fail_1

  analyze-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Backendend Analyze
          command: |
            cd backend
            npm install
      - run:
          name: Analyze the Backend
          command: |
            cd backend
            npm audit fix --audit-level=critical --force
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  default:
    jobs:
      - build-frontend
      - test-frontend:
          requires: 
            - build-frontend
      - analyze-frontend:
          requires:
            - test-frontend

      - build-backend
      - test-backend:
          requires: 
            - build-backend
      - analyze-backend:
          requires:
            - test-backend
